id = "helm"
name = "Helm"
version = "0.0.2"
schema_version = 1
authors = ["Alexey Kolegov <erste.13@gmail.com>"]
description = "Syntax highlighting for Helm templates"
repository = "https://github.com/erste/zed-helm"

[grammars.gotmpl]
repository = "https://github.com/ngalaiko/tree-sitter-go-template"
commit = "17144a77be0acdecebd9d557398883569fed41de"

# [grammars.gotmpl]
# repository = "https://github.com/qvalentin/tree-sitter-go-template"
# commit = "24e65deaf5e57b3042a5dbc1a6cf539fabee07fc"
