name = "Helm"
grammar = "gotmpl"
path_suffixes = ["yaml", "tpl"]
block_comment = ["{{/* ", " */}}"]
brackets = [
    { start = "{{", end = "}}", close = true, newline = false },
    { start = "{{-", end = "-}}", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
]
